### ISSUE TITLE
Maintenance script fails with Errors in 1.37

### ISSUE THREAD

**Issue by MTRNord** [octfx/wiki-seo#29]
Hi i tried to run the generateDescriptions script but it fails with some errors:

```
root@miki-en-mediawiki-678847567b-q2pnv:/var/www/html/extensions/WikiSEO# php maintenance/GenerateDescription.php 0
PHP Deprecated:  Use of Maintenance::getArg without an $argId was deprecated in MediaWiki 1.33. [Called from GenerateDescription::execute in /var/www/html/extensions/WikiSEO/maintenance/GenerateDescription.php at line 36] in /var/www/html/includes/debug/MWDebug.php on line 375
Deprecated: Use of Maintenance::getArg without an $argId was deprecated in MediaWiki 1.33. [Called from GenerateDescription::execute in /var/www/html/extensions/WikiSEO/maintenance/GenerateDescription.php at line 36] in /var/www/html/includes/debug/MWDebug.php on line 375
Generating description for 'Fluffychat'
[ec62bc12e624e3e9a26317fb] [no req]   TypeError: Argument 2 passed to MediaWiki\Extension\WikiSEO\DeferredDescriptionUpdate::__construct() must be of the type string or null, bool given, called in /var/www/html/extensions/WikiSEO/maintenance/GenerateDescription.php on line 84
Backtrace:
from /var/www/html/extensions/WikiSEO/includes/DeferredDescriptionUpdate.php(66)
#0 /var/www/html/extensions/WikiSEO/maintenance/GenerateDescription.php(84): MediaWiki\Extension\WikiSEO\DeferredDescriptionUpdate->__construct(Title, boolean)
#1 /var/www/html/maintenance/doMaintenance.php(108): GenerateDescription->execute()
#2 /var/www/html/extensions/WikiSEO/maintenance/GenerateDescription.php(93): require_once(string)
#3 {main}
```

**Comment by octfx** [comment]
Thanks for reporting!  
I'll fix this in the following days

**Comment by octfx** [comment]
Sorry forgot to ping you!
Should be fixed since da54743638d69e1ffa6d3e1b96be98bdaa2a0dd8

**Comment by MTRNord** [comment]
> Sorry forgot to ping you! Should be fixed since [da54743](https://github.com/octfx/wiki-seo/commit/da54743638d69e1ffa6d3e1b96be98bdaa2a0dd8)

Thanks 👍
